### ISSUE TITLE
Add clair 

### ISSUE THREAD

**Issue by patsevanton** [MrMEEE/harbor-rpm-ansible#5]
get error like https://github.com/quay/clair/issues/798

Disable notifier in clair
```
  notifier:
    attempts: 3
    renotifyinterval: 2h
    http:
      endpoint: http://localhost:8080/service/notifications/clair
```
